### ISSUE TITLE
WARNING: fwrite(): SSL: Broken pipe

### ISSUE THREAD

**Issue by mixian** [mikegioia/libremail#131]
Hi Mike,
I noticed that in the case in which the control on the mail account goes in block with the error in object "WARNING: fwrite (): SSL: Broken pipe", the system freezes and loop (in the folder) without however passing to the control of the next account (or folder).

**Comment by mikegioia** [comment]
I've encountered this one in the past, but not in this app. From what I gather, the broken pipe is a TCP protocol message and happens when you are trying to write into stream, but the remote site already closed the connection and didn't the client.

It could be a mail server restriction or a message that is too big for the mail server to send, or something like that. I don't think that error has anything to do with the client, thogh.

If you're able to view any logs or error info on the mail server, that would also be a good place to look.
